name = "Main Modded Server Pack Latest"
author = "Jeb_Kerm"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "be711b90d9888bb9a031d35374ffafb8d84d92ca76e91747097a223fedd87ed6"

[versions]
fabric = "0.18.1"
minecraft = "1.20.1"
