name = "Minecraft Server Test Pack"
author = "Jeb_Kerm"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "987f625ada6e2611bd3ccb994b93b1243bd268bd6c2d4292672acca7988dd250"

[versions]
fabric = "0.16.10"
minecraft = "1.21.4"

[options]
acceptable-game-versions = ["1.21.4"]
