name = "Main Pack Fabric Latest"
author = "Jeb_kerm"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "04b542cb7d2e3510e9e615ba17f06adb42c23341449c018136b4694957206c92"

[versions]
fabric = "0.16.14"
minecraft = "1.21.5"

[options]
acceptable-game-versions = ["1.21.5"]
